### PR TITLE
Support Python 3.12

### PR DESCRIPTION
**Pull request by alecandido**
Unfortunately work-in-progress

### CODE REVIEW

**Comment by alecandido** [comment]
Unfortunately, there is an *almost* circular dependency with `qibo`: it is `qibojit` that depends on `qibo`, that's why I'm trying to upgrade `qibo` first.
However, `qibo` depends on `qibojit` for the tests, that's why I mistakenly started from here (i.e. I tried first with `qibo` and it complained about `qibojit`, but I didn't investigate enough about why...)

**Comment by natestemen** [comment]
We're trying to support python 3.12 over on [`mitiq`](https://github.com/unitaryfund/mitiq) which has recently added Qibo as a dependency. I took a shot at supporting python 3.12 in Qibo and ran into the circular dependency issue as well. I'm not familiar enough with the project infrastructure to fully understand why, but let me know if there are any smaller things I can look into to help move this along!

**Comment by alecandido** [comment]
Sorry: I just interrupted because of other priorities. I thought no one needed py3.12 yet.

I believe I could make it by today (if not before). It's non-trivial, but still relatively simple.

**Comment by alecandido** [comment]
The related PR in Qibo
https://github.com/qiboteam/qibo/pull/1231

**Comment by alecandido** [comment]
@BrunoLiegiBastonLiegi @renatomello: apparently, there are issues linting the `quantum_info` module (here and not in Qibo...)
https://github.com/qiboteam/qibojit/actions/runs/8241315355/job/22538457740#step:10:1785
(among the others, of course they are not related to those purely coming from the Numba/CuPy backends)

**Comment by BrunoLiegiBastonLiegi** [comment]
> @BrunoLiegiBastonLiegi @renatomello: apparently, there are issues linting the `quantum_info` module (here and not in Qibo...) https://github.com/qiboteam/qibojit/actions/runs/8241315355/job/22538457740#step:10:1785 (among the others, of course they are not related to those purely coming from the Numba/CuPy backends)

weird, may be some problem with the lock?

**Comment by alecandido** [comment]
> weird, may be some problem with the lock?

The lock has no problem on its own, but you could inspect the locked Numba version.
https://github.com/qiboteam/qibojit/blob/8cfaea4ae63aa3cbf9aa9bd52d446f8dd48e23bc/poetry.lock#L486-L491

**Comment by alecandido** [comment]
Just waiting for https://github.com/qiboteam/qibo/pull/1231 to be merged

**Comment by alecandido** [comment]
@BrunoLiegiBastonLiegi @renatomello now that https://github.com/qiboteam/qibo/pull/1231 has been merged, we should be ready to merge this as well

**Review by BrunoLiegiBastonLiegi — APPROVED** [review]
Thanks @alecandido, I am probably not the most indicated person to look into this, but to me this is ready. Just a note on the `numba` and `pylint` version, the earliest version we support is changing because `python-3.12` does not support older versions?

**Comment by alecandido** [comment]
> Just a note on the `numba` and `pylint` version, the earliest version we support is changing because `python-3.12` does not support older versions?

Exactly :)

(Though it is better said the other way round: *older versions are not supporting py3.12*, because of the dependency arrow)

**Review by stavros11 — APPROVED** [review]

**Comment by alecandido** [comment]
Thanks! @stavros11 @BrunoLiegiBastonLiegi

**Comment by alecandido** [comment]
@natestemen now both Qibo and Qibojit are supporting py3.12 in `main`. Almost for sure, we'll get another release in less than one month.

**Pull request merged**
