### PR TITLE
Fix multiqubit GPU ops not called by JitCustomBackend

### PR DESCRIPTION
**Pull request by mlazzarin**
It looks like we forgot to update the call to the multiqubit GPU kernels in ``JitCustomBackend`` after we moved the latter from qibo to qibojit.

### CODE REVIEW

**Comment by mlazzarin** [comment]
I also made some changes in ``gates.py`` to improve readability. Let me know if you agree.

**Review by stavros11 — APPROVED** [review]
Thanks for finding this! Both the fix and the readability changes look good to me. 

I just hope that the previous fallback to CPU did not have any effect to the tests/benchmarks we were doing (thinking that we run on GPU but actually use CPU), although at least for the benchmarks I believe we would notice the difference from the results, particularly for high qibut numbers. Now it works in my machine and I can confirm that the multi-qubit GPU kernel is called during testing.

**Comment by scarrazza** [comment]
@mlazzarin thanks for these updates and fixes, looks good to me.

**Comment by mlazzarin** [comment]
> I just hope that the previous fallback to CPU did not have any effect to the tests/benchmarks we were doing (thinking that we run on GPU but actually use CPU), although at least for the benchmarks I believe we would notice the difference from the results, particularly for high qibut numbers.

@stavros11 I think the benchmarks of PR #23 and PR #37 are fine, because the fallback was removed in commit 58e1dfe98e8bdccbc5a0a054480cb72b9d722800 and re-introduced only in commit 3183df2c28c38235749f692e0b8025119f9ad8de, and the benchmarks were performed in the middle of the two commits. We may need to re-run the tests with the different configurations, though, but I usually do it every time a create a new environment, so it should be fine.

**Pull request merged**
