### PR TITLE
Adding signature with arrays

### PR DESCRIPTION
**Pull request by andrea-pasquale**
In this PR I implemented the explicit signature, as in #26, changing the `UniTuple` types to arrays.
Let me know if you are happy with these changes so that we can proceed with the benchmark.

### CODE REVIEW

**Comment by scarrazza** [comment]
@stavros11 I am getting the following for this PR:
```python
In [1]: %%time
   ...: from qibojit import custom_operators
   ...: 
   ...: 
OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
CPU times: user 29.6 s, sys: 107 ms, total: 29.7 s
Wall time: 29.7 s
```
using numba 0.54.1. I have noticed that this compilation happens only if we exclude GPU. This is probably not as fast as g++, but it is quite acceptable given the complexity of the task.

**Comment by stavros11** [comment]
> I have noticed that this compilation happens only if we exclude GPU. 

This is probably because if a GPU is available `from qibojit import custom_operators` will initialize the cupy backend only, since this is the default, and numba operators won't be compiled. On qibomachine I get 25sec for the initial compilation.

**Comment by scarrazza** [comment]
Very good, thanks for the confirmation.

**Comment by andrea-pasquale** [comment]
Nice to see that everything works fine in the qibo machine. Thanks for the benchmark.
I'm also fine with this PR.

**Comment by scarrazza** [comment]
Thanks.

**Pull request merged**
