### PR TITLE
Add missing stream synchronizations

### LINKED ISSUE #49: Kernel calls and thread synchronization
In ``CupyBackend`` the thread synchronization after kernel calls seems inconsistent.
In particular, it is used in ``one_qubit_base``, ``two_qubit_base`` and ``multi_qubit_base``, but it is not used in ``initial_state`` and ``collapse_state``.

If it is mandatory, we should add it where it's missing, otherwise we should remove it where it's unnecessary. What do you think?

### PR DESCRIPTION
**Pull request by mlazzarin**
Closes #49 .

### CODE REVIEW

**Comment by scarrazza** [comment]
Thanks, do you observe performance differences?

**Comment by mlazzarin** [comment]
I didn't check the performance, but @stavros11 and I noticed that all tests pass also if we remove ``self.cp.cuda.stream.get_current_stream().synchronize()`` in the whole code.

**Comment by mlazzarin** [comment]
@scarrazza how do you suggest to measure the performance of ``initial_state`` with or without synchronization?
Without synchronization I'm worried that the kernel will just execute asynchronously and we measure just the launch.

**Comment by scarrazza** [comment]
You could print the state and measure the full procedure, right?

**Comment by mlazzarin** [comment]
Yes, done it. I see no difference, if there is one it's smaller than the normal fluctuations of execution times in my laptop.

**Review by scarrazza — APPROVED** [review]
Thanks.

**Pull request merged**
