### PR TITLE
Fix cuquantum tests

### PR DESCRIPTION
**Pull request by stavros11**
Fixes qibo/abstractions tests when using cuquantum. 

@andrea-pasquale when you have time, could you please try to run all qibo (on `abstractions` branch) and qibojit tests using numba, cupy and cuquantum and confirm that everything is working? After this small fix, all is okay from my side.

It would also be great if we could test AMD HIP given that we promise this feature because I do not have access to an AMD GPU and I cannot test this.

### CODE REVIEW

**Comment by andrea-pasquale** [comment]
Sure @stavros11.
I'm currently trying to run tests on the qibomachine.
Do you remember the option to execute a job on GPU in slurm?
I believe that @scarrazza told me how to do so, but I can't remember.

**Comment by stavros11** [comment]
> Sure @stavros11. I'm currently trying to run tests on the qibomachine. Do you remember the option to execute a job on GPU in slurm? I believe that @scarrazza told me how to do so, but I can't remember.

For qibomachine it's 
```
sbatch -p heavysim launch.sh
```
where launch.sh is the bash script to be executed. For example for tests:
```sh
#!/bin/bash

pytest src/qibo
```

**Comment by andrea-pasquale** [comment]
> > Sure @stavros11. I'm currently trying to run tests on the qibomachine. Do you remember the option to execute a job on GPU in slurm? I believe that @scarrazza told me how to do so, but I can't remember.
> 
> For qibomachine it's
> 
> ```
> sbatch -p heavysim launch.sh
> ```
> 
> where launch.sh is the bash script to be executed. For example for tests:
> 
> ```shell
> #!/bin/bash
> 
> pytest src/qibo
> ```

Thanks!
But doesn't this execute the job only on CPU?

**Comment by stavros11** [comment]
> Thanks! But doesn't this execute the job only on CPU?

That's right. For GPU I think you need an additional option in sbatch:
```
sbatch -p heavysim --gres=gpu:0 launch.sh
```

**Comment by scarrazza** [comment]
This is working on AMD, @andrea-pasquale did you managed to run on yas?

**Review by scarrazza — APPROVED** [review]

**Comment by andrea-pasquale** [comment]
> This is working on AMD, @andrea-pasquale did you managed to run on yas?

The job is still queuing. We can also merge this and I'll open an issue if tests didn't pass.

**Comment by andrea-pasquale** [comment]
Tests are passing on the qibomachine (finally).

**Comment by stavros11** [comment]
Keep in mind that I pushed another fix yesterday that renames `get_state_tensor` -> `circuit_result_tensor` to be compatible with the latest qibo master. Tests should still be passing on both CPU and GPU.

**Pull request merged**
