### PR TITLE
Improving CuQuantum Implementation

### PR DESCRIPTION
**Pull request by andrea-pasquale**
In this PR I try to improve our cuquantum backend in order to reduce the dry run and the simulation time which are very different compared to our cupy backend in the case of some circuit like the QFT.

As suggested by the NVIDIA guys the implementation now uses only one handle which is initiated in the constructor and its destroyed in the destructor of the CuQuantum platform.

I'll upload some benchmarks shortly.

### CODE REVIEW

**Review by scarrazza — APPROVED** [review]
@andrea-pasquale thanks, looks good to me. If @stavros11 confirms, we can merge and prepare the release.

**Comment by andrea-pasquale** [comment]
Thanks for the benchmarks @stavros11 .
I'm happy to see that this approach works well also for the other circuits.
Maybe we can merge this PR and prepare the release, given that this branch is working, then we can think about the rest.
Let me know what you think.

**Comment by scarrazza** [comment]
>  We do something similar for numpy/tensorflow where we create a cache that holds the einsum string and we reuse without recalculating everytime the gate is called. I am not sure if this would provide any advantage but if yes it would only be visible in the second execution.

This is a good point, before merging this PR, may I suggest you to try of this approach locally (no PR) and see if there is some benefit in terms of performance?

**Comment by scarrazza** [comment]
@stavros11 thanks for this, quite interesting results, I had a quick look at your branch and it seems ok to me. @andrea-pasquale could you please have a look too? Then, if you all agree we can merge this PR and release a new version of qibojit.

**Comment by andrea-pasquale** [comment]
> @stavros11 thanks for this, quite interesting results, I had a quick look at your branch and it seems ok to me. @andrea-pasquale could you please have a look too? Then, if you all agree we can merge this PR and release a new version of qibojit.

Ok, I'll have a look.

**Comment by andrea-pasquale** [comment]
I agree with the changes in @stavros11 branch. I don't know if we can do something more to improve the simulation times. For the time being from my side we can merge both this one and @stavros11 branch.

**Pull request merged**
