### PR TITLE
Revert "Improving CuQuantum Implementation"

### PR DESCRIPTION
**Pull request by andrea-pasquale**
Reverts qiboteam/qibojit#72

### CODE REVIEW

**Comment by scarrazza** [comment]
@stavros11 I think at this point there is no evidence the handler improves performance so merging this PR could be a good compromise.

**Comment by stavros11** [comment]
Thanks for implementing this. Here are some benchmarks of this PR vs main:

<details>
<summary>My laptop - GTX 1650 - Driver 510.47.03 - CUDA 11.6</summary>

|   nqubits |   import main |  import revert |
|----------:|-------------------:|---------------------:|
|        18 |            1.92416 |              1.07401 |
|        20 |            1.49055 |              1.06188 |
|        22 |            1.43732 |              1.03434 |
|        24 |            1.36135 |              1.05886 |
|        26 |            1.41561 |              1.0647  |

|   nqubits |   dry run main |   dry run revert |
|----------:|--------------------:|----------------------:|
|        18 |            0.499222 |              1.06112  |
|        20 |            0.212105 |              0.886386 |
|        22 |            0.405883 |              1.02399  |
|        24 |            1.32294  |              2.06476  |
|        26 |            5.36723  |              6.24001  |

|   nqubits |   simulation main |   simulation revert |
|----------:|-----------------------------:|-------------------------------:|
|        18 |                    0.0141946 |                       0.106591 |
|        20 |                    0.0547338 |                       0.177938 |
|        22 |                    0.254491  |                       0.417552 |
|        24 |                    1.16326   |                       1.36397  |
|        26 |                    5.30492   |                       5.58353  |

|   nqubits |   total dry run main |   total dry run revert |
|----------:|----------------------:|------------------------:|
|        18 |               2.42944 |                 2.14204 |
|        20 |               1.71021 |                 1.95575 |
|        22 |               1.85175 |                 2.06643 |
|        24 |               2.69391 |                 3.13357 |
|        26 |               6.79435 |                 7.31709 |

</details>


<details>
<summary>DGX - Driver 460.91.03 - CUDA 11.2</summary>

|   nqubits |   import main |   import revert |
|----------:|-------------------:|---------------------:|
|        20 |            2.12862 |              1.62459 |
|        22 |            2.08757 |              1.61672 |
|        24 |            2.12456 |              1.61682 |
|        26 |            2.15422 |              1.62194 |
|        28 |            2.24709 |              1.59962 |
|        30 |            2.12944 |              1.62837 |

|   nqubits |   dry run main |   dry run revert |
|----------:|--------------------:|----------------------:|
|        20 |            0.268996 |               1.54529 |
|        22 |            0.294312 |               1.23975 |
|        24 |            0.448587 |               1.60995 |
|        26 |            1.17795  |               2.21529 |
|        28 |            4.32024  |               5.45572 |
|        30 |           17.986    |              19.3768  |

|   nqubits |   simulation main |   simulation revert |
|----------:|-----------------------------:|-------------------------------:|
|        20 |                    0.0278439 |                       0.324971 |
|        22 |                    0.0519684 |                       0.435224 |
|        24 |                    0.21755   |                       0.730232 |
|        26 |                    0.944422  |                       1.44973  |
|        28 |                    4.10013   |                       4.68074  |
|        30 |                   17.8011    |                      18.644    |

|   nqubits |   total dry run main |   total dry run revert |
|----------:|----------------------:|------------------------:|
|        20 |               2.40968 |                 3.18138 |
|        22 |               2.38658 |                 2.87051 |
|        24 |               2.58903 |                 3.24309 |
|        26 |               3.35066 |                 3.85462 |
|        28 |               6.58835 |                 7.07536 |
|        30 |              20.1394  |                21.0288  |

</details>

The import time issue is fixed here, but overally the total dry run is slightly faster with main. Personally I have no strong preference on this. I will add qibomachine benchmarks later because now I am running the large QFT benchmark there.

**Comment by andrea-pasquale** [comment]
I also don't have a strong preference. If we proceed with the revert I suggest that we keep this branch with the handler so that we can always come back to this version if needed.

**Comment by scarrazza** [comment]
Ok, then lets proceed with the main branch / release for the final plots.

**Comment by scarrazza** [comment]
@andrea-pasquale shall we close this PR at this point?

**Comment by andrea-pasquale** [comment]
> @andrea-pasquale shall we close this PR at this point?

For the time being I think yes. If in the future we will have a machine more similar to dom we can always reopen this PR.

**Pull request closed without merging**
